---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: product
  namespace: default
spec:
  destination:
    name: product
  sources:
  - name: search
    peer: dc1-default
    action: allow