apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: ingress-gateway
  namespace: default
spec:
  destination:
    name: search
  sources:
  - name: ingress-gateway
    action: allow
