apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default ## The name of the partition containing the service
spec:
  services:
  - name: product ## The name of the service you want to export
    consumers:
    - samenessGroup: default ## Specifies as sameness group to export the service to