apiVersion: consul.hashicorp.com/v1alpha1 # required
kind: SamenessGroup # required
metadata:
  name: default
spec:
  defaultForFailover: true
  members:
    - partition: default # required
    - peer: dc1-default